# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-08 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Album',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_id', models.IntegerField()),
                ('url', models.URLField()),
                ('media_url', models.URLField(blank=True, null=True)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='.')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.Album')),
            ],
            options={
                'verbose_name': 'Image',
                'ordering': ['-twitter_id'],
                'verbose_name_plural': 'Image',
            },
        ),
    ]
